version: '2.1'
services:
  spark-master:
    hostname: spark-master
    image: bde2020/spark-master:2.4.3-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "8020:8020"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "SPARK_PUBLIC_DNS=spark-master"
      - "SPARK_LOCAL_HOSTNAME=spark-master"
      - "SPARK_IDENT_STRING=spark-master"
    volumes:
      - /Users/andrea/Documents/sviluppo/git_aruba/spark-demo/target:/opt/spark-apps
    depends_on:
      - kafkaspark

  spark-worker-1:
    image: bde2020/spark-worker:2.4.3-hadoop2.7
    container_name: spark-worker-1
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_PUBLIC_DNS=spark-worker"
      - "STANDALONE_SPARK_MASTER_HOST=spark-master"
      - "SPARK_LOCAL_HOSTNAME=spark-worker"
      - "SPARK_IDENT_STRING=spark-worker"